- ngff_zarr/to_multiscales.py
- test/test_ngff_image_scale_factors.py
Results in a dask.array chunk size of 0, which causes errors.
> BUG: Do not add another scale after min_length scale_factor reached

- .gitignore
- ngff_zarr/__about__.py
- ngff_zarr/cli.py
- ngff_zarr/to_multiscales.py
- ngff_zarr/zarr_metadata.py
commit c6a655b3d656c02a9a1ded784f1605b56f350f7a (HEAD -> support-units-input, tbirdso/support-units-input)
Author: Tom Birdsong <tom.birdsong@kitware.com>
Date:   Mon May 1 11:17:10 2023 -0400
BUG: Fix rich input validation printouts to console
Resolves issue where CLI would crash silently and not print expected
validation messages to console when bad input parameters were parsed.
commit 6d48c12706cd22c69a8ce723626b6d1a94075942
Author: Tom Birdsong <tom.birdsong@kitware.com>
Date:   Fri Apr 28 17:11:38 2023 -0400
ENH: Add support for setting axis units from CLI
Allows setting units in output OME-Zarr file. Includes validation to
ensure that units match existing allowable type hints.
Addresses issue where output with "null" units could not be loaded in
viewer applications such as …
> ENH: Add support for setting axis units from CLI

- ngff_zarr/from_ngff_zarr.py
Some OME-Zarr written by other tools do not have this metadata member.
> BUG: Relax expectation of '@type' when reading other store metadata

- ngff_zarr/cli.py
Resolves issue where attempting to resolve units input against a non-existent units dictionary from the input file would cause the CLI to error out.
> BUG: Set units dictionary from CLI instead of updating existing

- ngff_zarr/methods/_dask_image.py
This fixes #40.
Commit history implies you were aware of this issue before, so make sure I didn't misunderstand anything:
https://github.com/thewtex/ngff-zarr/commit/7796b71db9831763c0bb066d6e2b6b79ce34e84b
I renamed `previous_dim_factors` to `previous_absolute_dim_factors`, since we need these numbers to be relative to the full resolution data, not relative to the previous scale level as before. Name change is good since `previous_absolute_dim_factors` is no longer equal to the previous iteration `dim_factors`.
This fixes my test case:
> absolute vs. relative scales bug fix in _dim_scale_factors

- pyproject.toml
This provides most common codecs for the tifffile package.
Suggested by: Davis Vann Bennett <davis.v.bennett@gmail.com>
Addresses #38
@d-v-b please take a look
> ENH: Add imagecodecs as a cli dependency

- ngff_zarr/methods/_dask_image.py
- ngff_zarr/to_multiscales.py
- ngff_zarr/to_ngff_zarr.py
This fixes the second comment in: https://github.com/thewtex/ngff-zarr/issues/45
> More dimension_separator="/" added, so napari can open big data as well

- ngff_zarr/to_ngff_zarr.py
This fixes https://github.com/thewtex/ngff-zarr/issues/45
I noticed calls to `to_zarr` in the `to_multiscales` function as well, but I think they're just cache for large files and not meant as ome-ngff-zarr outputs so I did not add a dimension separator for them.
You can also specify the dimension separator when you create the array (i.e. `zarr.creation.open_array`) but since you don't always do this explicitly I let the `dask.array.to_zarr` function do it.
Not sure if you want the dimension separator to be a user settable thing instead of hardcoded like this? If it's going to be standard practice for ome-ngff-zarr to use '/' and if some programs won't even support '.' then maybe compulsory like this is better, but your choice.
> nested separator in to_ngff_zarr, fixed napari display problem

- ngff_zarr/to_ngff_zarr.py
- test/_data.py
- test/test_from_ngff_zarr.py
Paths are '0', '1', etc. -- not the minimum two component paths required to create a NetCDF compatible OME-Zarr. Detect and avoid.
We do not have scale_factors if we did not generate the multiscales -- do not run logic for generating multiscales when scale_factors is not present.
> BUG: Support reading and writing an OME-Zarr created by omero-zarr

- pyproject.toml
Adds:
https://github.com/InsightSoftwareConsortium/itk-wasm/pull/1117/commits/ffb6e2cf6c8b5c3f064c16d5d51636cd85a59eae
> ENH: Bump itkwasm-downsample to support more label image types

- ngff_zarr/methods/_itk.py
- ngff_zarr/methods/_itkwasm.py
- ngff_zarr/methods/_support.py
- ngff_zarr/to_multiscales.py
- test/test_ngff_image_scale_factors.py
I tried running `to_multiscales` with `scale_factors=113` and experienced my script hanging.
While debugging I pinpointed that the `while` in `_ngff_image_scale_factors` is infinite looping.
This was because `while (sizes_array > double_chunks).any()` was comparing `[30 113 113]` to `[226 60 226]`. Or in some runs, `[226 226 60]` or `[60 226 226]`. In other words, `double_chunks` was randomly ordered.
I traced this back to the set `_spatial_dims = {"x", "y", "z"}` being used in comprehension expressions in a way that pulls values out of the set. Sets in Python are [not ordered](https://stackoverflow.com/questions/26420945/what-is-the-order-of-elements-in-a-python-set), and it looks like in practice I really was getting the values out of the set in a random order.
This PR fixes all usages …
> Fix usages of Sets

- .github/workflows/test.yml
- pixi.lock
- pyproject.toml
macos-14 for matrix.os instead of mac-14. And we want to run always for
not macos-14 and for macos-15 when python is 3.9 or greater.
> BUG: Fix CI macos-14 matrix exclusion logic

- ngff_zarr/to_ngff_zarr.py
- pixi.lock
- test/test_to_ngff_zarr_rfc2_zarr_v3.py
- test/test_to_ngff_zarr_tensorstore.py
> ENH: tensorstore Zarr 3, OME-Zarr 0.5 support

- ngff_zarr/from_ngff_zarr.py
- ngff_zarr/spec/0.1/copyright.include
- ngff_zarr/spec/0.1/schemas/image.schema
- ngff_zarr/spec/0.1/schemas/plate.schema
- ngff_zarr/spec/0.1/schemas/strict_image.schema
- ngff_zarr/spec/0.1/schemas/well.schema
- ngff_zarr/spec/0.2/copyright.include
- ngff_zarr/spec/0.2/schemas/image.schema
- ngff_zarr/spec/0.2/schemas/plate.schema
- ngff_zarr/spec/0.2/schemas/well.schema
- ngff_zarr/spec/0.3/copyright.include
- ngff_zarr/spec/0.3/schemas/image.schema
- ngff_zarr/spec/0.3/schemas/jsonld/context.json
- ngff_zarr/spec/0.3/schemas/jsonld/frame.json
- ngff_zarr/spec/0.3/schemas/jsonld/shacl.ttl
- ngff_zarr/spec/0.3/schemas/plate.schema
- ngff_zarr/spec/0.3/schemas/salad_schema/image.yml
- ngff_zarr/spec/0.3/schemas/strict_image.schema
- ngff_zarr/spec/0.3/schemas/well.schema
- test/_data.py
- test/test_ngff_validation.py
- ENH: Support reading and validating OME-Zarr v0.1
- ENH: Support reading and validating OME-Zarr v0.2
- ENH: Support reading and validating OME-Zarr v0.3
- ENH: Update test data hashes
> version 0.1 to 0.3

- README.md
- docs/index.md
- test/test_ngff_validation.py
- BUG: Remove commented test code
- DOC: Update feature list
> doc updates

- ngff_zarr/cli.py
- BUG: CLI zarr.storage imports for zarr-python 3.0.0b2
- ENH: Add --use-tensorstore flag to CLI
- ENH: Add --ome-zarr-version CLI flag
> tensorstore cli

- ngff_zarr/zarr_metadata.py
Re-provides the default OME-Zarr version zarr metadata at the same
module location for backwards compatibility, issue #122.
> BUG: Add ngff_zarr.zarr_metadata backwards compatibility module

- ngff_zarr/ngff_image_to_itk_image.py
- test/test_ngff_image_to_itk_image.py
Can either result in a spatial dimension + 1 dimension ITK Image or a
time index can be specified.
> ENH: Support time in ngff_image_to_itk_image

- .github/workflows/test.yml
- ngff_zarr/to_ngff_zarr.py
- pixi.lock
- test/test_to_ngff_zarr_rfc2_zarr_v3.py
- BUG: Pass Zarr Python 3 format_kwargs to open_array, dask
- COMP: Update pixi.lock for zarr-python 3.0.0
> zarr python 3 0 0

- docs/conf.py
I'm hoping that this configuration value ([see sphinx docs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-maximum_signature_line_length)) will improve reability of long signatures like [`to_multiscales`](https://ngff-zarr.readthedocs.io/en/latest/apidocs/ngff_zarr/ngff_zarr.to_multiscales.html#ngff_zarr.to_multiscales.to_multiscales).
> Add line breaks to long signatures in docs

- .github/workflows/pixi-test.yml
- ngff_zarr/to_ngff_zarr.py
- pixi.lock
- test/test_to_ngff_zarr_sharding.py
- **COMP: Update pixi.lock**
- **ENH: Zarr-Python sharding**
> zarr python sharding

- ngff_zarr/from_ngff_zarr.py
- ngff_zarr/v04/zarr_metadata.py
- test/test_omero.py
This pull request introduces a new optional `label` attribute to the `OmeroChannel` dataclass in line with the NGFF [0.4](https://ngff.openmicroscopy.org/0.4/index.html#omero-md) and [0.5](https://ngff.openmicroscopy.org/0.5/index.html#omero-md) specifications.
Updates related functions and tests to accommodate this change. The most important changes include modifications to the `OmeroChannel` class, the `from_ngff_zarr` function, and the `test_omero.py` test cases.
The OME-Zarr spec already supports the "label" string of a channel. This feature is useful because it makes it easy to include channel labels while writing `multiscales` data.
> Add channel labels

- .github/workflows/pixi-test.yml
- ngff_zarr/to_ngff_zarr.py
- pixi.lock
- test/test_to_ngff_zarr_sharding.py
- COMP: Update pixi.lock for 0.45.0
- ENH: Tensorstore sharding support
> tensorstore sharding

- test/_data.py
For: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bafybeib2s7ls6yscm2uqxby5vbhbfsyxn3ev7soewi3hji4uiki7v6cbiy.ipfs.w3s.link', port=443): Read timed out.
> COMP: Switch test data ipfs gateway to ipfs.io

- ngff_zarr/to_ngff_zarr.py
- test/_data.py
Zarr-Python 3 will use a dimension separator of / by default with
zarr_format = 3, which is used with OME-Zarr 0.5. However, we do need to
specify the dimension_separator explicity with Zarr-Python 3 and
OME-Zarr 0.4 when zarr_format 2 is used.
> BUG: Use dimension_separator == / with OME-Zarr 0.4, zarr-python 3

- ngff_zarr/methods/_itk.py
- ngff_zarr/methods/_itkwasm.py
- ngff_zarr/methods/_support.py
- test/test_pyramid_integrity.py
Changed to assignment of `previous_dim_scale_factors` to make it consistent. Addresses the issue raised here:  https://github.com/thewtex/ngff-zarr/issues/149
> Added a failing test and the code to make it not fail.

- ngff_zarr/to_ngff_zarr.py
- pixi.lock
- test/test_to_ngff_zarr_tensorstore.py
> BUG: Large tensorstore already-exists failure

- ts/src/io/from_ngff_zarr.ts
- ts/src/types/zarr_metadata.ts
- ts/test/from_ngff_zarr_test.ts
Improved OMERO metadata compatibility.
> test(ts): extend from_ngff_zarr_test
